---
title: "Capítulo 8"
subtitle: "Español 2"
author: "Nicole Rodríguez"
institute: "Middlebury College"
date: "2022/8/4 (updated: `r Sys.Date()`)"
output:
  xaringan::moon_reader:
    css: [default, middlebury, middlebury-fonts]
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---
class: center, inverse, middle

# Unidad 8

---
# Nuestro Plan

- Wordle 

- Revisar tarea

- Repasar cláusulas adverbiales y adjetivales

- Pronombres (doble objeto) 

- Más allá: pp. 226-228 act. 1-4

---

class: center, middle, inverse
# Wordle

https://wordle.danielfrg.com/

---
class: center, middle, inverse

# Tarea - ¿Preguntas?

---
class: middle, center

# Repasar cláusulas adverbiales y adjetivales

---
# Cláusulas adjetivales 

1. Tengo un amigo que (ser) muy honesto con la gente.

2. Busco a alguien que (ser) considerado.

3. No necesitamos más personas que (distraerse) en el trabajo.

4. Conocemos a personas que (distraerse) muy fácilmente en el trabajo.

5. ¿Conoces a alguien que (saber) hablar chino e italiano?

6. Sí, creo que hay alguien que (saber) hablar estos dos idiomas.

7. He leído que las personas que (ser) negativas también (ser) pesimistas en su forma de ver el mundo.

8. No conozco a nadie que (ser) tan inteligente como María Elena.

---
# Cláusulas adjetivales 

Los ciudadanos quieren que la ciudad (crear) más espacios verdes, (limpiar) las calles, (construir) más escuelas públicas y (ofrecer) ayuda a más necesitados.

Los estudiantes desean que la biblioteca de la universidad (cerrar) más tarde, (abrir) los fines de semana y (tener) espacios de estudio.

Los jóvenes necesitan que (haber)
 wifi gratuito y más enchufes en las aulas de la universidad.

Los padres buscan escuelas infantiles que (ser) gratuitas, (tener) buenos maestros, (poder) estar abiertas hasta tarde y (servir) comida para los niños.

---
# Más :) 

Hola, Alicia:

¿Cómo estás? Espero que [tú] (estar) bien. Te escribo porque he decidido pasar un mes más en España y si es posible quiero que (venir) por unas semanas a ver las maravillas de este país.

Dudo que (poder) venir ahora, pero de todas formas espero que (saber) que me encantaría verte aquí.

Mis amigos me recomiendan (explorar) la región de Andalucía antes de irme.  He escuchado que Sevilla y Granada (ser) dos ciudades que debo visitar.  No pienso (quedarse) más de 3 días porque también espero (visitar) la Costa del Sol y (nadar) en las aguas cristalinas del Mar Mediterráneo.

Es una pena que no [tú] (tener) la oportunidad de venir ahora pero tomaré muchas fotos por ti.

Besos,

Tu amiga Elena

---
# Cláusulas adverbiales

1. ¿Vamos por el túnel o por la montaña? Lo vamos a saber cuando el guía nos _______ (decir).
2. ¿Nos vemos en mi casa o en la tuya? Donde tú _______ (preferir).
3. ¿Para qué trabajaba tanto? Para que sus hijos _______ (poder) estudiar.
4. ¿Cómo hago el postre? De la manera que te _______ (parecer) mejor.
5. ¿Conversaban por teléfono fijo o por celular? De las dos maneras, según _______ (ser) conveniente.
6. ¿Por qué no te despediste de ellos? Es que se fueron sin que yo me _______ (dar) cuenta.
7. ¿Esperamos a Juan o nos vamos sin él? Como ustedes _______ (querer).
8. ¿Por qué está fría la sopa? Porque la serví mucho antes de que tú _______ (llegar).
9. ¿Por qué no comiste en casa? Es que no quería esperar hasta que la comida _______ (estar) lista.
10. Por favor llámame el lunes aunque _______ (ser) tarde.

---
# Cláusulas adverbiales

1. (organizar) Nos vamos a reunir para _______ una fiesta sorpresa para María.
2. (dar) Va a ser en casa de Pedro, con tal de que sus padres nos _______ permiso.
3. (saber) Queremos planear la fiesta sin que ella lo _______.
4. (llegar) Vamos a preparar todo antes de que _______ los invitados.
5. (ir) Pero no vamos a tener nada listo a menos que _______ de compras pronto.
6. (necesitar) Debemos llevar la tarjeta de crédito en caso de _______la.
7. (ver) Creo que María se va a sorprender mucho cuando ______ la fiesta que preparamos.
8. (salir) Pedro nos va a llamar en cuanto ella _______ de la oficina.
9. (tener) Así podremos estar listos sin _______ que preocuparnos por la hora.

---
class: center, middle

# PPT de pronombres (doble objeto)

---
# Actividad 25 = ¿Quién?

En parejas, una persona le hace preguntas sobre su vida a la otra. La que contesta debe usar pronombres de complemento directo e indirecto cuando sea posible. Cuando terminen, cambien de papel. 

Ejemplo: ¿Quién te manda SMS graciosos? Nadie me los manda | Mi amigo X me los manda.

.pull-left[
- quién te reenvía emails de otras personas

- quién te manda flores

- a quién le mandas emails breves

- quién te da regalos que te gustan
]

.pull-right[
- quién te da regalos que no te gustan 

- a quién le das consejos amorosos 

- quién te echa de menos
]

---
# Actividad 26 - La vida universitaria 

En parejas, túrnense para hacerse preguntas sobre su vida universitaria. Al contestar deben usar pronombres de complemento directo e indirecto cuando sea posible. 

1. si alguien le prestó el dinero para la universidad 

2. si recibió una beca al graduarse de la escuela secundaria

3. si la universidad le ofreció una beca

4. quién le da consejos para seleccionar las materias

5. dónde estudió español por primera vez

6. cuándo va a terminar su carrera

7. quién le explica las materias difíciles 

8. cuál de sus amigos lo/la ayuda más

---
class: middle, center 

# Repaso para la prueba


---
# Tarea


**F**

Estudiar voc: pp. 234 y 235

Estudiar: Subjuntivo en cláusulas adv. 2 p. 239

Contestar: p. 240 act. 11 A

**SAM**

Pp. 111-112 act. 18, p. 112 act. 19      

ct. 1, p. 117 act. 4, pp. 118 y 119 act. 7 y 8
---
class: center, middle, inverse 

# Día 2

---
# Nuestro plan

- Prueba 3

- Pasantías p. 232 act. 1 y 2

- El trabajo p. 235 act. 4 p. 236 act. 7

---
class: center, middle, inverse
# Wordle

https://wordle.danielfrg.com/

---
class: center, middle, inverse

# Tarea - ¿Preguntas?

---
class: center, middle

# Infograficos

---
# Actividad 3 - Trabajar fuera del país

1. ¿Conocen a alguien que haya trabajado en el extranjero? Si contestan que sí, ¿qué hizo esa persona? ¿Era una pasantía? ¿Cómo consiguió el trabajo? 

--

2. ¿Les gustaría trabajar en el extranjero? Si contestan que sí, ¿qué tipo de trabajo les gustaría hacer? ¿Adónde les gustaría ir?

---
# Historia laboral

1. ¿Han trabajado alguna vez? 

2. ¿Han tenido o tienen trabajo de tiempo complete con beneficios? Si contestan que sí, ¿qué beneficios recibieron o reciben? 

3. ¿Han trabajado a tiempo parcial? ¿Han trabajado solo durante los veranos? Si contestan que sí, ¿recibieron algunos beneficios?

4. ¿Cuál es el mejor o el peor trabajo que han tenido? Descríbanlo y expliquen por qué fue bueno o malo. 

5. Cuando nacieron, ¿estaba empleada su madre? Si contestan que sí, ¿dejó el puesto? ¿Le dieron licencia por maternidad? ¿Volvió a trabajar? ¿Trabajó a tiempo complete o a tiempo parcial? ¿Existía la oportunidad de pedie licencia por paternidad? Si contestan que sí, ¿la pidió su padre? 
---
# Actidad 8 - Opinamos

1. Todas la empresas deben tener guardería.

2. Debe hacer más cursos de capacitación para los desempleados. 

3. Es justo que las empresas bajen los sueldos para no tener que despedir a algunos empleados. 

4. Si una empresa tiene que despedir a algunos empleados, estos deben ser los últimos que se han contratado. 

5. Todo empleado de tiempo complete debe tener seguro médico y un mes de vacaciones pagadas cada año. 

---
# Tarea

**F**

- Estudiar: Discurso indirecto pp.243

- Contestar: p. 244 act. 16

- Estudiar: Negaciones y opciones p. 247

**SAM**

-P. 115 a

